### ISSUE TITLE
Documentation pages are not loading and website is down

### ISSUE THREAD

**Issue by tkdphoenix** [date-fns/date-fns.org#179] opened 2021-02-08 17:21 UTC
I have tried multiple ways to get to a page in documentation for date-fns with no success. When I go to this address: https://date-fns.org/v2.16.1/docs or this address: https://date-fns.org/v2.16.1/docs/getMonth I get the message "Failed to load package list!". Please review

**Comment by tkdphoenix** [comment] 2021-02-25 22:36
I am in Phoenix, Arizona, USA and my ISP is Cox Cable. Now docs show a 404.

**Comment by leshakoss** [comment] 2021-03-02 06:52
Duplicate of #175

**Closed by leshakoss** 2021-03-02 06:52 UTC
Labels: Support

**Comment by y471n** [comment] 2022-06-15 09:26
Encountering same problem from India today.

**Comment by Davydx7** [comment] 2022-07-19 09:08
Having the same issue. Located in Nigeria

**Comment by The-CodeNinja** [comment] 2022-08-18 08:02
+1 from India

**Comment by rafaelbpa** [comment] 2023-07-09 19:46
Same here. Can't see the docs right now. Tried every browser...

**Comment by JRixGeromo** [comment] 2023-07-09 23:30
Same here. Can't see the docs right now. Tried every browser too...

**Comment by The-CodeNinja** [comment] 2023-07-10 06:03
Using Safari worked for me

**Comment by pedro-mass** [comment] 2023-11-30 21:18
Happening again today... Is there a status page?

**Comment by hisreal123** [comment] 2024-03-01 19:11
is there a fix to this yet, I've been tryingg this for an hr+, anyone got a way into the doc. i need help with that. Thanks

**Comment by ScorpyG** [comment] 2024-09-03 18:46
Hey guys, still experiencing this issue when trying to access `https://date-fns.org/docs/Getting-Started`. The landing page seems fine.

I tried on `Brave v1.69.160` & `Safari` with and without the VPN. Does anyone else still have this issue?

**Comment by hisreal123** [comment] 2024-09-03 21:43
The page is working now without VPN.

**Comment by ScorpyG** [comment] 2024-09-03 21:47
@hisreal123 Maybe this is just an issue with my mac... Not sure if this is replicable.

![Screenshot 2024-09-03 at 2 45 08 PM](https://github.com/user-attachments/assets/41e37e08-1c2b-4cd8-b868-38a89a38f063)

**Comment by githero20** [comment] 2024-11-18 22:28
https://date-fns.org/docs/Getting-Started

Same for me, doesn't open and this is not the first time. I believe it could be an ISP thing, trying to access the site from Nigeria.
