### ISSUE TITLE
Documentations down

### ISSUE THREAD

**Issue by ninty9notout** [date-fns/date-fns.org#184] opened 2021-02-20 17:12 UTC
Potentially down to Firebase error as shown in console:

![image](https://user-images.githubusercontent.com/377860/108603222-a5e1d580-739e-11eb-883f-a50593fbf36b.png)

**Comment by ninty9notout** [comment] 2021-02-22 13:55
@tan75 West Midlands, United Kingdom (near Birmingham) and SSE broadband (they run off the BT line)

**Comment by leshakoss** [comment] 2021-03-02 06:53
Duplicate of #175

**Closed by leshakoss** 2021-03-02 06:53 UTC
