### ISSUE TITLE
Docs site not loading

### ISSUE THREAD

**Issue by SC7639** [date-fns/date-fns.org#182] opened 2021-02-13 11:28 UTC
When trying to open the docs site I'm getting  at first "loading..." then after a few seconds get "Failed to load package list!" and a console error, shown in the screenshot below

![image](https://user-images.githubusercontent.com/6049560/107848825-853ddc80-6dee-11eb-8fdc-c9be06507347.png)

**Comment by leshakoss** [comment] 2021-03-02 06:53
Duplicate of #175

**Closed by leshakoss** 2021-03-02 06:53 UTC
